services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: inventory-management
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: dummypassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  app:
    image: ghcr.io/0xzer0x/inventory-management:0.1
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DATASOURCE_URL: "jdbc:postgresql://db:5432/inventory-management"
      DATASOURCE_USERNAME: spring
      DATASOURCE_PASSWORD: dummypassword
    restart: unless-stopped

volumes:
  db-data:
