spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
